### ISSUE TITLE
Cannot create working VM reconfiguration request using the API

### ISSUE THREAD

**Issue by evertmulder** [ManageIQ/manageiq-api#260]
I try to reconfigure a VM using the API using the /api/requests API
I post the following body:
```json
{  
   "action":"create",
   "options":{  
      "src_ids":[  
         "80000000000078"
      ],
      "request_type":"vm_reconfigure",
      "disk_add":[  
         {  
            "disk_size_in_mb":"20",
            "persistent":true,
            "thin_provisioned":false,
            "dependent":true,
            "bootable":false
         }
      ]
   },
   "auto_approve":false
}
```

The request is accepted, but is not handled by the VMWare provider, I receive the following error message:
```
Error: add_disk_config_spec: Disk size is required to add a new disk.
```

Investigating this issue comes down the API inserts the reconfiguration request different than the classic-ui. When looking in the database (miq_requests.options) inserted using the UI:
```yaml
---
:src_ids:
- '80000000000078'
:disk_add:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  disk_size_in_mb: '15'
  persistent: true
  thin_provisioned: true
  new_controller_type: VirtualLsiLogicController
  dependent: true
  bootable: false
:request_type: :vm_reconfigure
```

Request inserted using the API in database (miq_requests.options) 
```yaml
---
:src_ids:
- '80000000000078'
:request_type: vm_reconfigure
:disk_add:
- disk_size_in_mb: '20'
  persistent: true
  thin_provisioned: false
  dependent: true
  bootable: false
:delivered_on: 2018-01-04 14:59:14.289655000 Z
```

Using the API the **!ruby/hash:ActiveSupport::HashWithIndifferentAccess** is missing.
The providers read the options using tokens leading to the exception.

This could be fixed by changing possible all providers, or inserting the options not as a regular hash.
